const CONSTANTS = {
  MODULE_ID: "fuzzy-foundry-lib",
  PATH: `modules/fuzzy-foundry-lib/`,
  FLAGS: {},
  API: {},
  FILEPICKER_PLUS_MODULE_ID: "filepicker-plus",
  VALID_EXTENSIONS: [
    ".jpg",
    ".JPG",
    ".jpeg",
    ".JPEG",
    ".png",
    ".PNG",
    ".svg",
    ".SVG",
    ".webp",
    ".WEBP",
    ".mp4",
    ".MP4",
    ".ogg",
    ".OGG",
    ".webm",
    ".WEBM",
    ".m4v",
    ".M4V",
    ".mp3",
    ".MP3",
    ".wav",
    ".WAV",
    ".flac",
    ".FLAC",
    ".aac",
    ".AAC",
    ".m4a",
    ".M4A",
    ".ogg",
    ".OGG",
    ".glb",
    ".GLB",
    ".gltf",
    ".GLTF",
    ".fbx",
    ".FBX",
  ],
};

CONSTANTS.PATH = `modules/${CONSTANTS.MODULE_ID}/`;

export default CONSTANTS;
